// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesSystem.Infrastructure.DbContextNamespace;

#nullable disable

namespace SalesSystem.Infrastructure.Migrations
{
    [DbContext(typeof(VentasDbContext))]
    [Migration("20260308212445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesSystem.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dispositivos electrónicos, smartphones, computadoras y accesorios tecnológicos",
                            Estado = true,
                            Nombre = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Prendas de vestir, calzado y accesorios de moda para toda la familia",
                            Estado = true,
                            Nombre = "Ropa y Moda"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Productos alimenticios no perecibles, granos, enlatados y snacks",
                            Estado = true,
                            Nombre = "Alimentos"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Bebidas gaseosas, jugos, aguas y bebidas energéticas",
                            Estado = true,
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Artículos para el hogar, decoración, ropa de cama y utensilios",
                            Estado = true,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Equipos deportivos, ropa deportiva y accesorios para el ejercicio",
                            Estado = true,
                            Nombre = "Deportes"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Juguetes educativos y de entretenimiento para niños de todas las edades",
                            Estado = true,
                            Nombre = "Juguetes"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Libros técnicos, novelas, materiales educativos y papelería",
                            Estado = true,
                            Nombre = "Libros y Educación"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Herramientas manuales, eléctricas y equipos para construcción y mantenimiento",
                            Estado = true,
                            Nombre = "Herramientas"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Productos de belleza, cuidado personal y fragancias",
                            Estado = true,
                            Nombre = "Cosméticos"
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "luis.castillo@mail.com",
                            Direccion = "Av. 10 de Agosto N34-451, Quito",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Luis Castillo",
                            NumeroDocumento = "1723456780",
                            Telefono = "0991234567",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "patricia.herrera@mail.com",
                            Direccion = "Calle Rocafuerte 234, Guayaquil",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Patricia Herrera",
                            NumeroDocumento = "0812345679",
                            Telefono = "0984567890",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "fernando.mendoza@mail.com",
                            Direccion = "Calle Bolívar 567, Cuenca",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Fernando Mendoza",
                            NumeroDocumento = "1345678901",
                            Telefono = "0975678901",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 4,
                            Correo = "gabriela.rios@mail.com",
                            Direccion = "Av. Amazonas 890, Quito",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Gabriela Ríos",
                            NumeroDocumento = "0756789012",
                            Telefono = "0966789012",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 5,
                            Correo = "ventas@comercialguerrero.com",
                            Direccion = "Calle Chile 123, Quito",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Comercial Guerrero",
                            NumeroDocumento = "1467890123001",
                            Telefono = "0957890123",
                            TipoDocumento = "RUC"
                        },
                        new
                        {
                            Id = 6,
                            Correo = "valentina.salazar@mail.com",
                            Direccion = "Av. 9 de Octubre 456, Guayaquil",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Valentina Salazar",
                            NumeroDocumento = "0978901234",
                            Telefono = "0948901234",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 7,
                            Direccion = "Calle Pichincha 789, Ambato",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Esteban Naranjo",
                            NumeroDocumento = "1589012345",
                            Telefono = "0939012345",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 8,
                            Correo = "c.cabrera@mail.com",
                            Direccion = "Av. Eloy Alfaro 012, Loja",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Cristina Cabrera",
                            NumeroDocumento = "P1234567",
                            Telefono = "0920123456",
                            TipoDocumento = "Pasaporte"
                        },
                        new
                        {
                            Id = 9,
                            Correo = "rodrigo.pacheco@mail.com",
                            Direccion = "Calle Sucre 345, Ibarra",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Rodrigo Pacheco",
                            NumeroDocumento = "1701234567",
                            Telefono = "0911234567",
                            TipoDocumento = "Cédula"
                        },
                        new
                        {
                            Id = 10,
                            Direccion = "Av. Universitaria 678, Santo Domingo",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Melissa Delgado",
                            NumeroDocumento = "9999999999",
                            TipoDocumento = "Consumidor Final"
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1m,
                            PrecioUnitario = 450.00m,
                            ProductoId = 1,
                            SubTotal = 450.00m,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 3m,
                            PrecioUnitario = 25.00m,
                            ProductoId = 2,
                            SubTotal = 75.00m,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 10m,
                            PrecioUnitario = 1.50m,
                            ProductoId = 3,
                            SubTotal = 15.00m,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 12m,
                            PrecioUnitario = 2.00m,
                            ProductoId = 4,
                            SubTotal = 24.00m,
                            VentaId = 4
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 2m,
                            PrecioUnitario = 35.00m,
                            ProductoId = 5,
                            SubTotal = 70.00m,
                            VentaId = 5
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 2m,
                            PrecioUnitario = 30.00m,
                            ProductoId = 6,
                            SubTotal = 60.00m,
                            VentaId = 6
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 1m,
                            PrecioUnitario = 45.00m,
                            ProductoId = 7,
                            SubTotal = 45.00m,
                            VentaId = 7
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 2m,
                            PrecioUnitario = 40.00m,
                            ProductoId = 8,
                            SubTotal = 80.00m,
                            VentaId = 8
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 1m,
                            PrecioUnitario = 85.00m,
                            ProductoId = 9,
                            SubTotal = 85.00m,
                            VentaId = 9
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 3m,
                            PrecioUnitario = 22.00m,
                            ProductoId = 10,
                            SubTotal = 66.00m,
                            VentaId = 10
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.FormadePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormadePago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = true,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Estado = true,
                            Nombre = "Tarjeta de Crédito"
                        },
                        new
                        {
                            Id = 3,
                            Estado = true,
                            Nombre = "Tarjeta de Débito"
                        },
                        new
                        {
                            Id = 4,
                            Estado = true,
                            Nombre = "Transferencia Bancaria"
                        },
                        new
                        {
                            Id = 5,
                            Estado = true,
                            Nombre = "Pago Móvil"
                        },
                        new
                        {
                            Id = 6,
                            Estado = true,
                            Nombre = "Cheque"
                        },
                        new
                        {
                            Id = 7,
                            Estado = true,
                            Nombre = "PayPal"
                        },
                        new
                        {
                            Id = 8,
                            Estado = false,
                            Nombre = "Criptomoneda"
                        },
                        new
                        {
                            Id = 9,
                            Estado = true,
                            Nombre = "Cuotas Sin Interés"
                        },
                        new
                        {
                            Id = 10,
                            Estado = true,
                            Nombre = "Vale / Bono"
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Codigo = "8806094691351",
                            Descripcion = "Teléfono inteligente 6.4\" FHD+, 128GB, 8GB RAM, cámara 50MP",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Smartphone Samsung Galaxy A54",
                            PrecioCompra = 320.00m,
                            PrecioVenta = 450.00m,
                            Stock = 25m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Codigo = "7890123456781",
                            Descripcion = "Camisa polo de algodón piqué, tallas S-XXL, colores variados",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Camisa Polo Sport",
                            PrecioCompra = 12.00m,
                            PrecioVenta = 25.00m,
                            Stock = 80m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Codigo = "7702014003014",
                            Descripcion = "Arroz blanco de grano largo, primera calidad, bolsa de 1 kilogramo",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Arroz Diana 1kg",
                            PrecioCompra = 0.90m,
                            PrecioVenta = 1.50m,
                            Stock = 500m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Codigo = "5449000000996",
                            Descripcion = "Bebida gaseosa sabor cola, botella PET de 2 litros",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Coca-Cola 2 Litros",
                            PrecioCompra = 1.10m,
                            PrecioVenta = 2.00m,
                            Stock = 300m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Codigo = "8901234567891",
                            Descripcion = "Juego de sábanas 100% algodón 200 hilos, sábana plana, ajustable y 2 fundas",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Set de Sábanas Queen Size",
                            PrecioCompra = 18.00m,
                            PrecioVenta = 35.00m,
                            Stock = 40m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 6,
                            Codigo = "4056562008927",
                            Descripcion = "Balón oficial de fútbol talla 5, cuero sintético resistente",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1614632537190-23e4146777f9?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Balón de Fútbol Adidas",
                            PrecioCompra = 16.00m,
                            PrecioVenta = 30.00m,
                            Stock = 60m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 7,
                            Codigo = "5702016370768",
                            Descripcion = "Set de construcción con 500 piezas de colores variados para niños +4 años",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?auto=format&fit=crop&w=500&q=60",
                            Nombre = "LEGO Classic 500 Piezas",
                            PrecioCompra = 25.00m,
                            PrecioVenta = 45.00m,
                            Stock = 35m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 8,
                            Codigo = "9780132350884",
                            Descripcion = "Libro técnico sobre buenas prácticas de programación y código limpio, edición en inglés",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Clean Code - Robert C. Martin",
                            PrecioCompra = 20.00m,
                            PrecioVenta = 40.00m,
                            Stock = 20m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 9,
                            Codigo = "3165140571746",
                            Descripcion = "Taladro eléctrico de percusión 600W, incluye juego de brocas y maletín",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Taladro Percutor Bosch 600W",
                            PrecioCompra = 52.00m,
                            PrecioVenta = 85.00m,
                            Stock = 15m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 10,
                            Codigo = "0773602072453",
                            Descripcion = "Labial mate de larga duración, tono Ruby Woo, presentación 3g",
                            Estado = true,
                            ImagenUrl = "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=500&q=60",
                            Nombre = "Labial MAC Ruby Woo",
                            PrecioCompra = 10.00m,
                            PrecioVenta = 22.00m,
                            Stock = 50m
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Sistema",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "admin@admin.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "1234567890",
                            Nombre = "Admin",
                            Rol = 1
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "García",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "ana.garcia@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0912345671",
                            Nombre = "Ana",
                            Rol = 2
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodríguez",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "carlos.rodriguez@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "1723456782",
                            Nombre = "Carlos",
                            Rol = 1
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "López",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "maria.lopez@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0823456793",
                            Nombre = "María",
                            Rol = 2
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Martínez",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "jose.martinez@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "1334567894",
                            Nombre = "José",
                            Rol = 2
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Sánchez",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "laura.sanchez@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0745678905",
                            Nombre = "Laura",
                            Rol = 1
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Pérez",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "roberto.perez@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "1456789016",
                            Nombre = "Roberto",
                            Rol = 2
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Torres",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "diana.torres@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0967890127",
                            Nombre = "Diana",
                            Rol = 2
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Flores",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "miguel.flores@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "1578901238",
                            Nombre = "Miguel",
                            Rol = 2
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Vargas",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "sofia.vargas@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0689012349",
                            Nombre = "Sofía",
                            Rol = 1
                        },
                        new
                        {
                            Id = 11,
                            Apellido = "Morales",
                            Contraseña = "$2a$12$aSrDuKNoTg8yxrvgJQau3elFMpmYy49Jy2oBawO2hpMpcv5bk9pIy",
                            Email = "andres.morales@ventas.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "1790123450",
                            Nombre = "Andrés",
                            Rol = 2
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormadePagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImpuestoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormadePagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 1,
                            ImpuestoTotal = 54.00m,
                            NumeroComprobante = "COMP-2024-001",
                            SubTotal = 450.00m,
                            Total = 504.00m,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 2,
                            ImpuestoTotal = 9.00m,
                            NumeroComprobante = "COMP-2024-002",
                            SubTotal = 75.00m,
                            Total = 84.00m,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 1,
                            ImpuestoTotal = 1.80m,
                            NumeroComprobante = "COMP-2024-003",
                            SubTotal = 15.00m,
                            Total = 16.80m,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 4,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 3,
                            ImpuestoTotal = 2.88m,
                            NumeroComprobante = "COMP-2024-004",
                            SubTotal = 24.00m,
                            Total = 26.88m,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 5,
                            ClienteId = 5,
                            Descuento = 5m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 4,
                            ImpuestoTotal = 7.80m,
                            NumeroComprobante = "COMP-2024-005",
                            SubTotal = 70.00m,
                            Total = 72.80m,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 6,
                            ClienteId = 6,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 1,
                            ImpuestoTotal = 7.20m,
                            NumeroComprobante = "COMP-2024-006",
                            SubTotal = 60.00m,
                            Total = 67.20m,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 7,
                            ClienteId = 7,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 2,
                            ImpuestoTotal = 5.40m,
                            NumeroComprobante = "COMP-2024-007",
                            SubTotal = 45.00m,
                            Total = 50.40m,
                            UsuarioId = 9
                        },
                        new
                        {
                            Id = 8,
                            ClienteId = 8,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 5,
                            ImpuestoTotal = 9.60m,
                            NumeroComprobante = "COMP-2024-008",
                            SubTotal = 80.00m,
                            Total = 89.60m,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 9,
                            ClienteId = 9,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 4,
                            ImpuestoTotal = 10.20m,
                            NumeroComprobante = "COMP-2024-009",
                            SubTotal = 85.00m,
                            Total = 95.20m,
                            UsuarioId = 11
                        },
                        new
                        {
                            Id = 10,
                            ClienteId = 10,
                            Descuento = 0m,
                            Estado = true,
                            FechaVenta = new DateTime(2024, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormadePagoId = 3,
                            ImpuestoTotal = 7.92m,
                            NumeroComprobante = "COMP-2024-010",
                            SubTotal = 66.00m,
                            Total = 73.92m,
                            UsuarioId = 7
                        });
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("SalesSystem.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesSystem.Domain.Entities.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SalesSystem.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Venta", b =>
                {
                    b.HasOne("SalesSystem.Domain.Entities.FormadePago", "FormadePago")
                        .WithMany()
                        .HasForeignKey("FormadePagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesSystem.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("FormadePago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SalesSystem.Domain.Entities.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
